/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CollapseIcon: typeof import('./src/components/icons/CollapseIcon.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    MenuList: typeof import('./src/components/MenuList.vue')['default']
    PipeIcon: typeof import('./src/components/icons/PipeIcon.vue')['default']
    QuillIcon: typeof import('./src/components/icons/QuillIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsIcon: typeof import('./src/components/icons/SettingsIcon.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
    WorldviewsIcon: typeof import('./src/components/icons/WorldviewsIcon.vue')['default']
    WritersIcon: typeof import('./src/components/icons/WritersIcon.vue')['default']
  }
}

// For TSX support
declare global {
  const CollapseIcon: typeof import('./src/components/icons/CollapseIcon.vue')['default']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCard: typeof import('element-plus/es')['ElCard']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElDropdown: typeof import('element-plus/es')['ElDropdown']
  const ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
  const ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElPagination: typeof import('element-plus/es')['ElPagination']
  const ElTooltip: typeof import('element-plus/es')['ElTooltip']
  const MenuList: typeof import('./src/components/MenuList.vue')['default']
  const PipeIcon: typeof import('./src/components/icons/PipeIcon.vue')['default']
  const QuillIcon: typeof import('./src/components/icons/QuillIcon.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SettingsIcon: typeof import('./src/components/icons/SettingsIcon.vue')['default']
  const Test: typeof import('./src/components/Test.vue')['default']
  const WorldviewsIcon: typeof import('./src/components/icons/WorldviewsIcon.vue')['default']
  const WritersIcon: typeof import('./src/components/icons/WritersIcon.vue')['default']
}